language: android
android:
   components:
     - android-21
     - build-tools-21.1.2

     - platform-tools

     - sys-img-armeabi-v7a-android-15
     - sys-img-armeabi-v7a-android-21
     - sys-img-x86-android-21
